# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.votes import Votes  # noqa: F401,E501
from swagger_server import util


class CreateShortRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, category: str=None, title: str=None, author: str=None, publish_date: datetime=None, content: str=None, actual_content_link: str=None, image: str=None, votes: Votes=None):  # noqa: E501
        """CreateShortRequest - a model defined in Swagger

        :param category: The category of this CreateShortRequest.  # noqa: E501
        :type category: str
        :param title: The title of this CreateShortRequest.  # noqa: E501
        :type title: str
        :param author: The author of this CreateShortRequest.  # noqa: E501
        :type author: str
        :param publish_date: The publish_date of this CreateShortRequest.  # noqa: E501
        :type publish_date: datetime
        :param content: The content of this CreateShortRequest.  # noqa: E501
        :type content: str
        :param actual_content_link: The actual_content_link of this CreateShortRequest.  # noqa: E501
        :type actual_content_link: str
        :param image: The image of this CreateShortRequest.  # noqa: E501
        :type image: str
        :param votes: The votes of this CreateShortRequest.  # noqa: E501
        :type votes: Votes
        """
        self.swagger_types = {
            'category': str,
            'title': str,
            'author': str,
            'publish_date': datetime,
            'content': str,
            'actual_content_link': str,
            'image': str,
            'votes': Votes
        }

        self.attribute_map = {
            'category': 'category',
            'title': 'title',
            'author': 'author',
            'publish_date': 'publish_date',
            'content': 'content',
            'actual_content_link': 'actual_content_link',
            'image': 'image',
            'votes': 'votes'
        }
        self._category = category
        self._title = title
        self._author = author
        self._publish_date = publish_date
        self._content = content
        self._actual_content_link = actual_content_link
        self._image = image
        self._votes = votes

    @classmethod
    def from_dict(cls, dikt) -> 'CreateShortRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateShortRequest of this CreateShortRequest.  # noqa: E501
        :rtype: CreateShortRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def category(self) -> str:
        """Gets the category of this CreateShortRequest.


        :return: The category of this CreateShortRequest.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this CreateShortRequest.


        :param category: The category of this CreateShortRequest.
        :type category: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def title(self) -> str:
        """Gets the title of this CreateShortRequest.


        :return: The title of this CreateShortRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this CreateShortRequest.


        :param title: The title of this CreateShortRequest.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this CreateShortRequest.


        :return: The author of this CreateShortRequest.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this CreateShortRequest.


        :param author: The author of this CreateShortRequest.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def publish_date(self) -> datetime:
        """Gets the publish_date of this CreateShortRequest.


        :return: The publish_date of this CreateShortRequest.
        :rtype: datetime
        """
        return self._publish_date

    @publish_date.setter
    def publish_date(self, publish_date: datetime):
        """Sets the publish_date of this CreateShortRequest.


        :param publish_date: The publish_date of this CreateShortRequest.
        :type publish_date: datetime
        """
        if publish_date is None:
            raise ValueError("Invalid value for `publish_date`, must not be `None`")  # noqa: E501

        self._publish_date = publish_date

    @property
    def content(self) -> str:
        """Gets the content of this CreateShortRequest.


        :return: The content of this CreateShortRequest.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this CreateShortRequest.


        :param content: The content of this CreateShortRequest.
        :type content: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def actual_content_link(self) -> str:
        """Gets the actual_content_link of this CreateShortRequest.


        :return: The actual_content_link of this CreateShortRequest.
        :rtype: str
        """
        return self._actual_content_link

    @actual_content_link.setter
    def actual_content_link(self, actual_content_link: str):
        """Sets the actual_content_link of this CreateShortRequest.


        :param actual_content_link: The actual_content_link of this CreateShortRequest.
        :type actual_content_link: str
        """

        self._actual_content_link = actual_content_link

    @property
    def image(self) -> str:
        """Gets the image of this CreateShortRequest.


        :return: The image of this CreateShortRequest.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this CreateShortRequest.


        :param image: The image of this CreateShortRequest.
        :type image: str
        """

        self._image = image

    @property
    def votes(self) -> Votes:
        """Gets the votes of this CreateShortRequest.


        :return: The votes of this CreateShortRequest.
        :rtype: Votes
        """
        return self._votes

    @votes.setter
    def votes(self, votes: Votes):
        """Sets the votes of this CreateShortRequest.


        :param votes: The votes of this CreateShortRequest.
        :type votes: Votes
        """

        self._votes = votes
