# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CreateShortResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, short_id: str=None, status_code: int=None):  # noqa: E501
        """CreateShortResponse - a model defined in Swagger

        :param message: The message of this CreateShortResponse.  # noqa: E501
        :type message: str
        :param short_id: The short_id of this CreateShortResponse.  # noqa: E501
        :type short_id: str
        :param status_code: The status_code of this CreateShortResponse.  # noqa: E501
        :type status_code: int
        """
        self.swagger_types = {
            'message': str,
            'short_id': str,
            'status_code': int
        }

        self.attribute_map = {
            'message': 'message',
            'short_id': 'short_id',
            'status_code': 'status_code'
        }
        self._message = message
        self._short_id = short_id
        self._status_code = status_code

    @classmethod
    def from_dict(cls, dikt) -> 'CreateShortResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateShortResponse of this CreateShortResponse.  # noqa: E501
        :rtype: CreateShortResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this CreateShortResponse.


        :return: The message of this CreateShortResponse.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this CreateShortResponse.


        :param message: The message of this CreateShortResponse.
        :type message: str
        """

        self._message = message

    @property
    def short_id(self) -> str:
        """Gets the short_id of this CreateShortResponse.


        :return: The short_id of this CreateShortResponse.
        :rtype: str
        """
        return self._short_id

    @short_id.setter
    def short_id(self, short_id: str):
        """Sets the short_id of this CreateShortResponse.


        :param short_id: The short_id of this CreateShortResponse.
        :type short_id: str
        """

        self._short_id = short_id

    @property
    def status_code(self) -> int:
        """Gets the status_code of this CreateShortResponse.


        :return: The status_code of this CreateShortResponse.
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code: int):
        """Sets the status_code of this CreateShortResponse.


        :param status_code: The status_code of this CreateShortResponse.
        :type status_code: int
        """

        self._status_code = status_code
