# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ErrorResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, status_code: int=None):  # noqa: E501
        """ErrorResponse - a model defined in Swagger

        :param status: The status of this ErrorResponse.  # noqa: E501
        :type status: str
        :param status_code: The status_code of this ErrorResponse.  # noqa: E501
        :type status_code: int
        """
        self.swagger_types = {
            'status': str,
            'status_code': int
        }

        self.attribute_map = {
            'status': 'status',
            'status_code': 'status_code'
        }
        self._status = status
        self._status_code = status_code

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorResponse of this ErrorResponse.  # noqa: E501
        :rtype: ErrorResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this ErrorResponse.


        :return: The status of this ErrorResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ErrorResponse.


        :param status: The status of this ErrorResponse.
        :type status: str
        """

        self._status = status

    @property
    def status_code(self) -> int:
        """Gets the status_code of this ErrorResponse.


        :return: The status_code of this ErrorResponse.
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code: int):
        """Sets the status_code of this ErrorResponse.


        :param status_code: The status_code of this ErrorResponse.
        :type status_code: int
        """

        self._status_code = status_code
