# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.short import Short  # noqa: F401,E501
from swagger_server.models.votes import Votes  # noqa: F401,E501
from swagger_server import util


class FilteredShort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, contains_title: bool=None, contains_content: bool=None, contains_author: bool=None, short_id: str=None, category: str=None, title: str=None, author: str=None, publish_date: datetime=None, content: str=None, actual_content_link: str=None, image: str=None, votes: Votes=None):  # noqa: E501
        """FilteredShort - a model defined in Swagger

        :param contains_title: The contains_title of this FilteredShort.  # noqa: E501
        :type contains_title: bool
        :param contains_content: The contains_content of this FilteredShort.  # noqa: E501
        :type contains_content: bool
        :param contains_author: The contains_author of this FilteredShort.  # noqa: E501
        :type contains_author: bool
        :param short_id: The short_id of this FilteredShort.  # noqa: E501
        :type short_id: str
        :param category: The category of this FilteredShort.  # noqa: E501
        :type category: str
        :param title: The title of this FilteredShort.  # noqa: E501
        :type title: str
        :param author: The author of this FilteredShort.  # noqa: E501
        :type author: str
        :param publish_date: The publish_date of this FilteredShort.  # noqa: E501
        :type publish_date: datetime
        :param content: The content of this FilteredShort.  # noqa: E501
        :type content: str
        :param actual_content_link: The actual_content_link of this FilteredShort.  # noqa: E501
        :type actual_content_link: str
        :param image: The image of this FilteredShort.  # noqa: E501
        :type image: str
        :param votes: The votes of this FilteredShort.  # noqa: E501
        :type votes: Votes
        """
        self.swagger_types = {
            'contains_title': bool,
            'contains_content': bool,
            'contains_author': bool,
            'short_id': str,
            'category': str,
            'title': str,
            'author': str,
            'publish_date': datetime,
            'content': str,
            'actual_content_link': str,
            'image': str,
            'votes': Votes
        }

        self.attribute_map = {
            'contains_title': 'contains_title',
            'contains_content': 'contains_content',
            'contains_author': 'contains_author',
            'short_id': 'short_id',
            'category': 'category',
            'title': 'title',
            'author': 'author',
            'publish_date': 'publish_date',
            'content': 'content',
            'actual_content_link': 'actual_content_link',
            'image': 'image',
            'votes': 'votes'
        }
        self._contains_title = contains_title
        self._contains_content = contains_content
        self._contains_author = contains_author
        self._short_id = short_id
        self._category = category
        self._title = title
        self._author = author
        self._publish_date = publish_date
        self._content = content
        self._actual_content_link = actual_content_link
        self._image = image
        self._votes = votes

    @classmethod
    def from_dict(cls, dikt) -> 'FilteredShort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FilteredShort of this FilteredShort.  # noqa: E501
        :rtype: FilteredShort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def contains_title(self) -> bool:
        """Gets the contains_title of this FilteredShort.


        :return: The contains_title of this FilteredShort.
        :rtype: bool
        """
        return self._contains_title

    @contains_title.setter
    def contains_title(self, contains_title: bool):
        """Sets the contains_title of this FilteredShort.


        :param contains_title: The contains_title of this FilteredShort.
        :type contains_title: bool
        """

        self._contains_title = contains_title

    @property
    def contains_content(self) -> bool:
        """Gets the contains_content of this FilteredShort.


        :return: The contains_content of this FilteredShort.
        :rtype: bool
        """
        return self._contains_content

    @contains_content.setter
    def contains_content(self, contains_content: bool):
        """Sets the contains_content of this FilteredShort.


        :param contains_content: The contains_content of this FilteredShort.
        :type contains_content: bool
        """

        self._contains_content = contains_content

    @property
    def contains_author(self) -> bool:
        """Gets the contains_author of this FilteredShort.


        :return: The contains_author of this FilteredShort.
        :rtype: bool
        """
        return self._contains_author

    @contains_author.setter
    def contains_author(self, contains_author: bool):
        """Sets the contains_author of this FilteredShort.


        :param contains_author: The contains_author of this FilteredShort.
        :type contains_author: bool
        """

        self._contains_author = contains_author

    @property
    def short_id(self) -> str:
        """Gets the short_id of this FilteredShort.


        :return: The short_id of this FilteredShort.
        :rtype: str
        """
        return self._short_id

    @short_id.setter
    def short_id(self, short_id: str):
        """Sets the short_id of this FilteredShort.


        :param short_id: The short_id of this FilteredShort.
        :type short_id: str
        """

        self._short_id = short_id

    @property
    def category(self) -> str:
        """Gets the category of this FilteredShort.


        :return: The category of this FilteredShort.
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category: str):
        """Sets the category of this FilteredShort.


        :param category: The category of this FilteredShort.
        :type category: str
        """

        self._category = category

    @property
    def title(self) -> str:
        """Gets the title of this FilteredShort.


        :return: The title of this FilteredShort.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this FilteredShort.


        :param title: The title of this FilteredShort.
        :type title: str
        """

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this FilteredShort.


        :return: The author of this FilteredShort.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this FilteredShort.


        :param author: The author of this FilteredShort.
        :type author: str
        """

        self._author = author

    @property
    def publish_date(self) -> datetime:
        """Gets the publish_date of this FilteredShort.


        :return: The publish_date of this FilteredShort.
        :rtype: datetime
        """
        return self._publish_date

    @publish_date.setter
    def publish_date(self, publish_date: datetime):
        """Sets the publish_date of this FilteredShort.


        :param publish_date: The publish_date of this FilteredShort.
        :type publish_date: datetime
        """

        self._publish_date = publish_date

    @property
    def content(self) -> str:
        """Gets the content of this FilteredShort.


        :return: The content of this FilteredShort.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this FilteredShort.


        :param content: The content of this FilteredShort.
        :type content: str
        """

        self._content = content

    @property
    def actual_content_link(self) -> str:
        """Gets the actual_content_link of this FilteredShort.


        :return: The actual_content_link of this FilteredShort.
        :rtype: str
        """
        return self._actual_content_link

    @actual_content_link.setter
    def actual_content_link(self, actual_content_link: str):
        """Sets the actual_content_link of this FilteredShort.


        :param actual_content_link: The actual_content_link of this FilteredShort.
        :type actual_content_link: str
        """

        self._actual_content_link = actual_content_link

    @property
    def image(self) -> str:
        """Gets the image of this FilteredShort.


        :return: The image of this FilteredShort.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image: str):
        """Sets the image of this FilteredShort.


        :param image: The image of this FilteredShort.
        :type image: str
        """

        self._image = image

    @property
    def votes(self) -> Votes:
        """Gets the votes of this FilteredShort.


        :return: The votes of this FilteredShort.
        :rtype: Votes
        """
        return self._votes

    @votes.setter
    def votes(self, votes: Votes):
        """Sets the votes of this FilteredShort.


        :param votes: The votes of this FilteredShort.
        :type votes: Votes
        """

        self._votes = votes
