# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LoginResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: str=None, status_code: int=None, user_id: str=None, access_token: str=None):  # noqa: E501
        """LoginResponse - a model defined in Swagger

        :param status: The status of this LoginResponse.  # noqa: E501
        :type status: str
        :param status_code: The status_code of this LoginResponse.  # noqa: E501
        :type status_code: int
        :param user_id: The user_id of this LoginResponse.  # noqa: E501
        :type user_id: str
        :param access_token: The access_token of this LoginResponse.  # noqa: E501
        :type access_token: str
        """
        self.swagger_types = {
            'status': str,
            'status_code': int,
            'user_id': str,
            'access_token': str
        }

        self.attribute_map = {
            'status': 'status',
            'status_code': 'status_code',
            'user_id': 'user_id',
            'access_token': 'access_token'
        }
        self._status = status
        self._status_code = status_code
        self._user_id = user_id
        self._access_token = access_token

    @classmethod
    def from_dict(cls, dikt) -> 'LoginResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LoginResponse of this LoginResponse.  # noqa: E501
        :rtype: LoginResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> str:
        """Gets the status of this LoginResponse.


        :return: The status of this LoginResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this LoginResponse.


        :param status: The status of this LoginResponse.
        :type status: str
        """

        self._status = status

    @property
    def status_code(self) -> int:
        """Gets the status_code of this LoginResponse.


        :return: The status_code of this LoginResponse.
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code: int):
        """Sets the status_code of this LoginResponse.


        :param status_code: The status_code of this LoginResponse.
        :type status_code: int
        """

        self._status_code = status_code

    @property
    def user_id(self) -> str:
        """Gets the user_id of this LoginResponse.


        :return: The user_id of this LoginResponse.
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: str):
        """Sets the user_id of this LoginResponse.


        :param user_id: The user_id of this LoginResponse.
        :type user_id: str
        """

        self._user_id = user_id

    @property
    def access_token(self) -> str:
        """Gets the access_token of this LoginResponse.


        :return: The access_token of this LoginResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this LoginResponse.


        :param access_token: The access_token of this LoginResponse.
        :type access_token: str
        """

        self._access_token = access_token
